name: Nightly Builds

# Basically an automated ./bin/export.sh

on:
  push:
    branches: [ dev, docker, main ]
  pull_request:
    branches: [ dev, main ]

permissions:
  contents: read
  actions: read

concurrency:
  group: branch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: x86_64
            skip_header_generation: false

          - os: linux
            arch: arm64
            skip_header_generation: true

          - os: linux
            arch: arm32
            skip_header_generation: true

          - os: windows
            arch: x86_64
            skip_header_generation: true

    name: ${{ matrix.os }}/${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          if [[ "${{ matrix.skip_header_generation }}" == "true" ]]; then
            ./bin/export.sh ${{ matrix.os }} ${{ matrix.arch }} --no-header
          else
            ./bin/export.sh ${{ matrix.os }} ${{ matrix.arch }}
          fi
      
      # test.sh builds the headers if the non linux x86_64 finish first.
      - name: Run tests
        run: ./bin/test.sh release ${{ matrix.os }} ${{ matrix.arch }}

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: libggui-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/export/libggui_${{ matrix.os }}_${{ matrix.arch }}.*

      - name: Upload headers
        if: matrix.skip_header_generation == false
        uses: actions/upload-artifact@v4
        with:
          name: headers
          path: bin/export/*.h
