name: Nightly Builds

# Basically a automated ./bin/export.sh with platformed tests.

on:
  push:
    branches: [ dev, docker, main ]
  pull_request:
    branches: [ dev, main ]

permissions:
  contents: read
  actions: read

concurrency:
  group: branch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  binaries:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            image: ubuntu-latest
            arch: x86_64

          - os: linux
            image: ubuntu-24.04-arm
            arch: arm64

          - os: linux
            image: ubuntu-latest  # our dockerfile will take care of the QEMU usage.
            arch: arm32

          - os: windows
            image: windows-latest
            arch: x86_64

    runs-on: ${{ matrix.image }}
    name: ${{ matrix.os }}/${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./bin/export.sh ${{ matrix.os }} ${{ matrix.arch }}

      - name: Test
        run: ./bin/test.sh release ${{ matrix.os }} ${{ matrix.arch }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libggui-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            bin/export/libggui*
            bin/export/*.h

      - name: Upload ggui log when fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs-${{ matrix.os }}-${{ matrix.arch }}
          path: ./bin/build-release-${{ matrix.os }}-${{ matrix.arch }}/log.txt
